### ISSUE TITLE
Issues in ProcessSurveyData.R and the README

### ISSUE THREAD

**Issue by esurface** [nealjean/predicting-poverty#1]
Hi! I am trying to reproduce your research to learn more about applied machine learning with satellite imagery. I ran into a few issues I thought you might want to hear:

First, in ProcessSurveyData.R, line 131 (for Malawi) two arguments are given for the nl function. I see that it takes two, but I get an unused argument error:

```
Error in nl(., mwi13.vars, 2013) : unused argument (2013)
In addition: There were 15 warnings (use warnings() to see them)
```

My guess from the other code is that there used to be multiple parameters to this function and the vars is no lnger needed and should be removed:

```
nl(mwi13.vars, 2013) -> nl(2013)
```

Second, in the README.md, you mention that the Tanzania data from LSMS should be relabeled to DATA:

```
  3. Unzip these files so that **data/input/LSMS** contains the following folders of data:
       1. UGA_2011_UNPS_v01_M_STATA
       2. DATA (formerly TZA_2012_LSMS_v01_M_STATA_English_labels before a re-upload in January 2016)
       3. NGA_2012_LSMS_v03_M_STATA
       4. MWI_2013_IHPS_v01_M_STATA
```

But in the code in ProcessSurveyData.R you have "DATA" as the directory for the Nigeria data:

```
## Nigeria ##
nga13.cons <- read.dta('data/input/LSMS/DATA/cons_agg_w2.dta') %$%
  data.frame(hhid = hhid, cons = pcexp_dr_w2/365)
nga13.cons$cons <- nga13.cons$cons*110.84/(79.53*100)
nga13.geo <- read.dta('data/input/LSMS/DATA/Geodata Wave 2/NGA_HouseholdGeovars_Y2.dta')
nga13.coords <- data.frame(hhid = nga13.geo$hhid, lat = nga13.geo$LAT_DD_MOD, lon = nga13.geo$LON_DD_MOD)
nga13.rururb <- data.frame(hhid = nga13.geo$hhid, rururb = nga13.geo$sector, stringsAsFactors = F)
nga13.weight <- read.dta('data/input/LSMS/DATA/HHTrack.dta')[,c('hhid', 'wt_wave2')]
names(nga13.weight)[2] <- 'weight'
nga13.phhh8 <- read.dta('data/input/LSMS/DATA/Post Harvest Wave 2/Household/sect8_harvestw2.dta')
nga13.room <- data.frame(hhid = nga13.phhh8$hhid, room = nga13.phhh8$s8q9)
nga13.metal <- data.frame(hhid = nga13.phhh8$hhid, metal = nga13.phhh8$s8q7=='IRON SHEETS')
nga13.elev <- raster('data/input/DIVA-GIS/NGA_alt.gri') %>%
  extract(., nga13.coords[,c('lon', 'lat')]) %>%
  data.frame(hhid = nga13.coords$hhid, elev = .) %>% na.omit()
```

Which should be fixed: the code or the README?

**Comment by wmadavis** [comment]
Hi esurface,

Thanks for reaching out. You're absolutely right that line 130 should read `nl(2013)`. This is a relic from rewriting the pipe operators for readability prior to making our repo public.

To your second point, the code is correct. We've now amended the ReadMe to reflect this. To be clear, the user should never need to manually relabel any data or folders.

Cheers!

Matt

**Comment by esurface** [comment]
Hi Matt,

Thanks for the quick response and fix. I ran into a few more items that should be quick fixes as well. Hope you don't mind me adding to the thread:
1. The user does need to manually relabel the folders in 'data/input/DHS' because they are time-stamped with the date of download. You may want to update the README.md to say that explicitly or change the code to be graceful with the file names (e.g. use UG_2011_DHS_\* to look up the folder in code).
2. Here is a diff (renamed to .txt) of other changes:
   [pred-pov.txt](https://github.com/nealjean/predicting-poverty/files/514432/pred-pov.txt)
   a. ProcessSurveyData.R, line 163 -> extra parenthesis
   b. get_image_download_locations.py, line 75 -> 'pixels' causes 'no global variable found' error. I expect it should be pixel
   c. get_image_download_locations.py, line 86 -> Nightlights data is in a directory for 2013
   d. save_survey_data.py -> I had to turn off sampling to use "full set of household clusters" or else the script failed

Those changes got me through to the part where I need to "download imagery from locations of interest". Did you get these from LANDSAT?

Best,
Erik

**Comment by sangmichaelxie** [comment]
Hi Erik,

Thanks for spotting 2a, 2b and 2c, those are corrected and pushed. We're
working on 2d.

Best,
Michael

**Comment by nealjean** [comment]
Hi Erik,

The CNN is trained on 400x400 pixel RGB images taken from the Google Static Maps API at zoom level 16. To access the API, you need to register for an API key here: https://console.developers.google.com

Hope that helps!

Neal

**Comment by esurface** [comment]
Thanks all! 

I'm sure you wrote a script to download the imagery. Any plan to include it?

**Comment by nealjean** [comment]
We're not planning to upload any code for downloading imagery because it's somewhat unclear whether that would be ok under Google's terms of use. Documentation for the Static Maps API can be found here though:

https://developers.google.com/maps/documentation/static-maps/

**Comment by esurface** [comment]
I thought that would be the case :) I'll write my own.
