### ISSUE TITLE
Training Data

### ISSUE THREAD

**Issue by mtz1402** [nealjean/predicting-poverty#11]
Hi,
In the third step to predict poverty, we require the survey data along with the corresponding extracted features. If so ,then we need some sort of corresponding training data for the images to predict poverty?  Then how can we calculate poverty or economic measure just using the daytime images?  I dont know if i am missing something?  My question is how can we predict some values of poverty or economic activity based on the daytime images without any survey or training data?

**Comment by sangmichaelxie** [comment]
See the section 

"Instructions for processing survey data"

in the README for survey data.

**Comment by mtz1402** [comment]
Thank you for the reply...i have the survey downloaded...but my question is if you compared the results that you achieved just by using satellite images' features with the results of survey (in other words, you used the survey's data as features to train regression model).

**Comment by sangmichaelxie** [comment]
We do this comparison in our earlier paper for the binary version of the problem, and our method approaches the survey results: 

https://arxiv.org/abs/1510.00098

**Comment by mtz1402** [comment]
Thank you
