### ISSUE TITLE
Missing Model Weights - FOUND

### ISSUE THREAD

**Issue by chrisyeh96** [nealjean/predicting-poverty#12]
The saved weights for the trained model are missing. In `extract_features.py` (see [here](https://github.com/nealjean/predicting-poverty/blob/master/scripts/extract_features.py#L139)) we expect the weights file to be located at `../model/predicting_poverty_trained.caffemodel`, but such a file does not exist in the repo.

**Comment by parthagar** [comment]
Hey Chris,
If you have the model weights could you please paste a link, if it's okay with you.

**Comment by nealjean** [comment]
Try this [link](https://www.dropbox.com/s/4cmfgay9gm2fyj6/predicting_poverty_trained.caffemodel?dl=0)

**Comment by parthagar** [comment]
Thanks a lot Neal. Implementing a research based on yours for India, and this will be a big help.

**Comment by LokenderSarna** [comment]
Hey Parth,
I am from Delhi. Also working on the same project. Can we do something collaboratively?
