### ISSUE TITLE
n*4096 features

### ISSUE THREAD

**Issue by Raf1010** [nealjean/predicting-poverty#13]
Hey
So i have extracted the n*4096 features from the satellite images. I was wondering if  all the features are meaningful for your poverty measure and from the output you know which feature represents what?

Also in one of your videos in youtube i saw the output you refer to is a linear combination of the features extracted..is that a summation of the features or something else.

**Comment by nealjean** [comment]
1. No, in general we do not know what the 4096 features represent, and not all of them are meaningful. We did visualize some of the features in the intermediate layers of the network though, and found that some of those are interpretable and intuitive.

2. We use the extracted features to train a regularized linear regression model to predict household consumption or asset index.

**Comment by mtz1402** [comment]
So the extracted features are then used with the survey data to predict the consumption or asset index?

**Comment by nealjean** [comment]
Yes, that's right.
