### ISSUE TITLE
how to Download imagery from locations of interest (e.g., cluster locations from Nigeria DHS survey). 

### ISSUE THREAD

**Issue by mscsedu** [nealjean/predicting-poverty#17]
Great work. but i am stuck at this point. i have run get_image_download_locations.py and after that i need to download imagery locations of interest. Do i need to download the imagery manually or any script is given?

thanks in advance

**Comment by nealjean** [comment]
You will need to download the imagery yourself

**Comment by mscsedu** [comment]
Thanks for your kind reply. As i have lat lon values and clusters lat lon values around 25000 for one contry. So how can i download images? By writing scripts or by using another source?

**Comment by nealjean** [comment]
We downloaded our daytime satellite imagery using the [Google Static Maps API](https://developers.google.com/maps/documentation/static-maps/)

**Comment by mscsedu** [comment]
i tried to work with Google Static Maps API and i learned how to shows maps in webpage. I am new to maps and satellite imagery. kindly help me to download day time satellite images. As in DHS data Nigera has file candidate_download_loc.txt contains 25935 lat lon and cluster lat lon. how i will download all the images.
thanks in advance

**Comment by nealjean** [comment]
In accordance with the Google Maps APIs Terms of Service we've decided not to provide code for downloading daytime imagery - sorry!
