### ISSUE TITLE
Problem replicating results after using extract_features.py

### ISSUE THREAD

**Issue by djson8** [nealjean/predicting-poverty#18]
Hello,

I'm having some trouble replicating the figures after trying to `extract_features.py` myself, and am getting results looking like attached below for Figure 3 Cluster Level Consumptions:

![screen shot 2017-12-12 at 14 44 38](https://user-images.githubusercontent.com/34457024/33890456-3c39e8ec-df4b-11e7-9381-7db5b1d52d23.png)
![screen shot 2017-12-12 at 14 44 32](https://user-images.githubusercontent.com/34457024/33890457-3c65a6f8-df4b-11e7-9cc9-10460129dbe6.png)
![screen shot 2017-12-12 at 14 44 27](https://user-images.githubusercontent.com/34457024/33890458-3c9052b8-df4b-11e7-9d5d-1fd05f58e548.png)
![screen shot 2017-12-12 at 14 44 17](https://user-images.githubusercontent.com/34457024/33890460-3cd05688-df4b-11e7-994f-6a26fd9aef6c.png)

I'm pretty sure have followed all the steps correctly unless I missed something - do you have any idea what I may have done wrong?

Thanks!

**Comment by nealjean** [comment]
Not sure what is going wrong - it looks like your model is predicting roughly constant values for all locations. Some things that might be worth checking:

- Are you getting nonzero features for most locations?
- Are the labels matched with the locations? Make sure that things are not getting messed up when you are shuffling the data.

**Comment by djson8** [comment]
Thanks for getting back to me, will check those things.

Could be similar problem to #16?

**Comment by djson8** [comment]
Actually yes, a fix turned out to be what was described in #16 by reloading the net model after every batch. Slows it down a lot, but seems to work.
