### ISSUE TITLE
Out of sample training 

### ISSUE THREAD

**Issue by mtz1402** [nealjean/predicting-poverty#19]
Hey  I was able to train for some countries replicating your work. I want to do some out of sample predictions. I see you have used countries for the out of sample prediction which are similar in characteristics. Do you suggest we can use a model trained in a country which is very different economic development wise? For instance, using  a model trained with say  Netherlands to do out of sample training lets say for Nigeria?

**Comment by nealjean** [comment]
My guess is that a model trained in the Netherlands won't transfer very
well to Nigeria, but it would be interesting to try! We only worked with
data in Africa so our countries were all relatively similar - if it's
possible to train models in the developed world where lots of
measurements/data are available and apply them in data-poor countries, that
would be very cool!

**Comment by mtz1402** [comment]
Thanks...would probably then give a try.
