### ISSUE TITLE
Different output file names in different scripts

### ISSUE THREAD

**Issue by adymaharana** [nealjean/predicting-poverty#2]
Hi! 

The script 'extract_features.py' stores the CNN features and other aspects of the model as 'conv_features.npy' and 'image_counts.npy'. But, the modules 'load_country_lsms' and 'load_country_dhs' in 'fig_utils.py' seem to be looking for the files 'cluster_conv_features.npy' and 'cluster_image_counts.npy' and they are not being generated at any other point in the workflow. The same goes for 'nightlights.npy', 'consumptions.npy' and 'households.npy'. Am I missing something here, or are both the scripts supposed to be referring to the same file? 

Thanks

**Comment by nealjean** [comment]
Yes, these should be the same - thanks for catching that!
