### ISSUE TITLE
Why not getting good results?

### ISSUE THREAD

**Issue by mscsedu** [nealjean/predicting-poverty#21]
Hi Neal,
why I am not getting very good results. In following figure I have choose first 800 images from candicate_download_locs.txt and use them and then extract features and generate figure 3.

![nigeria](https://user-images.githubusercontent.com/33829224/42024079-cf6307b8-7ada-11e8-8984-6b566728bfda.png)

In following figure I have used cluster Lat Lon directly to download images and then extract features and generate figure 3.

![nigeria1](https://user-images.githubusercontent.com/33829224/42024341-604417ea-7adb-11e8-8ec7-ab2330376b5b.png)

could you please help me out? It would be highly appreciated

**Comment by nealjean** [comment]
Could be related to #18 and #16?

**Comment by mscsedu** [comment]
Sir could you please guide me how can I reload the net model after every batch to resolve the problem, as i am new in this field and just following your steps to get results.
Thanks

**Comment by nealjean** [comment]
Sorry, you'll have to figure this out on your own - we've since moved on from Caffe, I don't know how to do this either!

**Comment by mscsedu** [comment]
i have managed to sort the problem and got results. I have a question that why we are using information around the cluster by generating the locations and download the satellite images around the cluster. Why don't we use the direct locations given in survey.

**Comment by nealjean** [comment]
The survey locations have added jitter, so we use satellite images in a 10 km by 10 km square centered on the location to hopefully capture the true area occupied by the cluster
