### ISSUE TITLE
fig D - Tanzania differs

### ISSUE THREAD

**Issue by tomassa** [nealjean/predicting-poverty#22]
Hi Neal,

maybe not an issue, just a note.
After replication of Fig1 I noticed that in original paper - fig D Tanzania has much different shape than other countries.
Could be caused by not enough data points for higher consumption segment. Actually it looks like for Tanzania there is much more data for that period.

My figure for this country looks similar to Uganda and Nigeria. Can supply the fig if needed. Used the same data downloaded these days.

Btw, nice work, regards
Tom

**Comment by nealjean** [comment]
Sure, would be great to see the figure!

I can't remember what kind of model we used for these best fit lines but it looks like it doesn't extrapolate very well - to me the Tanzania and Uganda data (blue points) look pretty similar even though the black lines and grey shading don't?

In any case, seems like something could be improved here haha

**Comment by tomassa** [comment]
[Figure_1_20180801.pdf](https://github.com/nealjean/predicting-poverty/files/2250680/Figure_1_20180801.pdf)

**Comment by tomassa** [comment]
my produced output LSMS files with line counts, Tanzania cluster file is significantly big, which corresponds to the fig1:
501  - Nigeria 2013 LSMS (Cluster).txt 
4538 - Nigeria 2013 LSMS (Household).txt
930  - Malawi 2013 LSMS (Cluster).txt
4002 - Malawi 2013 LSMS (Household).txt
1526 - Tanzania 2013 LSMS (Cluster).txt
4863 - Tanzania 2013 LSMS (Household).txt
645  - Uganda 2012 LSMS (Cluster).txt
2732 - Uganda 2012 LSMS (Household).txt

**Comment by tomassa** [comment]
I just wanted to note it, do not think it is worth of wasting the time for further investigations. Currently there is more data -> should be able to make better predictions for Tanzania :)
