### ISSUE TITLE
Downloading images from Google Map API at correct coordinates

### ISSUE THREAD

**Issue by vinitveersingh** [nealjean/predicting-poverty#26]
Greetings Authors,
Thanks for sharing your code. As the README in the repository mentions the output of the candidate_download_locs.txt is in the form of [image_lat] [image_long] [cluster_lat] [cluster_long] and these coordinates generate locations meant to download 1x1 km RGB satellite images of size 400x400 pixels. In context to using Google Map API to download images, I am assuming that [image_lat], [image_long], [cluster_lat] and [cluster_long] were the rectangular coordinates of the Geometry object that were used to download the 400 x 400 image, i.e, top-left corner = {[image_lat], [image_long]} and bottom-left corner = {[cluster_lat], [cluster_long]}. To verify this assumption I used the haversine distance formula but I obtained areas greater that 25km in some cases. Now, I am assuming that you might have taken 1 km x 1km patches around the {[image_lat] , [image_long]} , i.e, considering {[image_lat] , [image_long]} as the center point. Is this what you had done or was some other method used? 
Thank you,
Vinit

**Comment by sangmichaelxie** [comment]
The cluster lat and long is the center coordinate, and the image lat and
longs are the coordinates for 1x1 patches around that center point. The
script should already generate multiple image lat and longs per cluster lat
and long.

**Comment by hans-ekbrand** [comment]
If I recall correctly, images are expected to be retrieved using zoom level = 16 using Google Static Image API, with the centerpoint given by candidate_download_locs.txt (as pointed out by @sangmichaelxie).

**Comment by vinitveersingh** [comment]
@sangmichaelxie @hans-ekbrand Thanks for both your replies. The confusion arose because I assumed the Google Static Image API and Google Earth Engine API worked the same way. I am not very familiar with Google Static Image API but after reading through the documentation and your comments I understand I just need to put in the [image_lat], [image_long] coordinates in their API at zoom level 16.  [cluster_lat], [cluster_long] play no part in the API itself but just aid in creating [image_lat], [image_long]. But how is the patch around [image_lat], [image_long] of size 1km x 1km still eludes me. Does zoom level 16 make the patch size equal to 1km x 1km?

**Comment by sangmichaelxie** [comment]
That's right. You will need cluster lat and long again when aggregating
features to cluster level though.
