### ISSUE TITLE
The host website for the World Bank's LSMS-ISA data is not accessible.

### ISSUE THREAD

**Issue by hlin863** [nealjean/predicting-poverty#28]
![image](https://github.com/nealjean/predicting-poverty/assets/55798830/424dbf63-fc1a-4946-805f-133f003e3790)
When attempting to access the World Bank's LSMS-ISA data through your link, an error message comes up as follows:
![image](https://github.com/nealjean/predicting-poverty/assets/55798830/3551c466-6380-4857-b2c4-68bf619c62fb)
Would you like to check if the site is accessible or has been updated to a new location?

Thanks and Kind Regards,
Haocheng

**Comment by nealjean** [comment]
hi Haocheng! unfortunately I haven't been keeping up with this for several years and can't really point you in the right direction. hope you're able to find where they're hosting the data now or a similar data source that you can use!
