### ISSUE TITLE
Cannot download the "Nigeria 2012-13" LSMS data

### ISSUE THREAD

**Issue by alexbernotas** [nealjean/predicting-poverty#3]
I'm following your process for "Instructions for processing survey data" and I hid a dead end when trying to download the "Nigeria 2012-13" LSMS data, both links to download the data that are provided on the "[host website for the World Bank's LSMS-ISA data](http://econ.worldbank.org/WBSITE/EXTERNAL/EXTDEC/EXTRESEARCH/EXTLSMS/0,,contentMDK:23512006%7EpagePK:64168445%7EpiPK:64168309%7EtheSitePK:3358997,00.html)" are not working for the country Nigeria ([link example](http://econ.worldbank.org/WBSITE/EXTERNAL/EXTDEC/EXTRESEARCH/EXTLSMS/0,,contentMDK:23635560~pagePK:64168445~piPK:64168309~theSitePK:3358997,00.html)), is there another place where I can download this data? or could you share the examples you used?

Thanks,
Alex

**Comment by wmadavis** [comment]
Hi Alex,

The Nigerian Bureau of Statistics normally also hosts the same data [here](http://www.nigerianstat.gov.ng/nada/index.php/catalog), but looks like it's also temporarily unavailable there. According to the data catalog, they've been uploading the newest round of Nigerian survey data over the past two days so this is likely just unfortunate timing and I'd expect both sites to fix the issue within the next few days.

Per the user agreement, we can't disseminate the data ourselves but if the issue persists past this week, let me know at wmdavis@stanford.edu.

In the meantime, it should be fairly straightforward to tweak the code to replicate the study without Nigeria's LSMS data.

Best,

Matt

**Comment by alexbernotas** [comment]
Thanks Matt,

Hopefully they will fix the links in the next few days, but in the meantime we have to wait to get access to the DHS data anyway (after registration it takes time for them to review our request to grant us access)

Thanks again,
Alex

**Comment by wmadavis** [comment]
Just as a quick update to this: I heard back from the folks at the World Bank yesterday and the Nigeria data should now be available again.

Matt
