### ISSUE TITLE
How to actually download satellite images?

### ISSUE THREAD

**Issue by alshedivat** [nealjean/predicting-poverty#5]
Hi there!

Thanks for the detailed description of how to get and process the data. It seems to me that the only missing piece is how to actually download the satellite images (and where to download them from). Is it possible to do that automatically using GDAL? It would be wonderful if you could to share the script you used to retrieve the images.

Thanks,
Maruan

**Comment by alshedivat** [comment]
Ok, I figured that the images are easy to download using Google Static Maps API. Though, a couple of questions: (1) Which exact zoom level did you use? Is it 16? (2) Each image comes with a copyright watermark at the bottom. The images shown in the paper seem to have no watermark. I am wondering if you further pre-processed the images by removing the watermark before training the model?

I'd appreciate your help.

**Comment by nealjean** [comment]
1) Zoom level 16
2) Yes, we just downloaded slightly larger images and then cropped them
