### ISSUE TITLE
Is the satellite imagery georeferenced?

### ISSUE THREAD

**Issue by mtz1402** [nealjean/predicting-poverty#7]
Hey I am looking into using satellite imagery to predict economic activity. I saw previous questions about how the images are downloaded. I just wanted to ask, if your images are georeferenced?

**Comment by sangmichaelxie** [comment]
They are georeferenced, since the images are downloaded by the locations.

**Comment by mtz1402** [comment]
Thanks for reply, so i believe you have used the latitude and longitude values for the center of the location?

**Comment by nealjean** [comment]
That's correct
