### ISSUE TITLE
the 2nd step

### ISSUE THREAD

**Issue by mtz1402** [nealjean/predicting-poverty#8]
Hey so for the 2nd step training step, night lights are used. Is that in image form or values ranging from 0 to 62? 
Also the second training step  predicts the nightlight intensities from the daytime images. So does that mean you also derive a new data set of predicted light intensity values  from your training along with the third row of images from figure 2?

**Comment by nealjean** [comment]
We bin the nightlights into 3 classes, so the labels should be "low", "medium", and "high".

You could produce predicted nightlight intensities from daytime imagery, but we only use the nightlights as a way to learn satellite image features.
