### ISSUE TITLE
Deriving specific filtered images

### ISSUE THREAD

**Issue by mtz1402** [nealjean/predicting-poverty#9]
Hi,
I have run the extract feature script on some images to derive the convolutional features and also  the filtered images. I was able to derive the n*4096 array conv_features.npy and the 64 filtered images. But  I see from Figure 2 of your paper, you have identified different convolutional filters. I was wondering if you ran a separate script to identify a specific convolutional feature such as roads, buildings, concrete structures etc.  In particular, I was wondering if it is possible to extract values (in a tabular format) that measure the total number of particular features in the image. For example, out of the total number of pixels, there are X pixels that have the features of concrete structures, Y pixels that are roads etc.

**Comment by sangmichaelxie** [comment]
We don't have a script that does this - we plotted the intermediate layer
activations and we manually inspected them. It seems that you would need
many other separate models that can detect roads and other features from
the acivations maps to be able to do what you are describing, which is
actually in the direction of something that we wanted to avoid using the
deep learning approach.

**Comment by mtz1402** [comment]
Thank you for getting back to me.
